spring:
  application:
    name: MM-quiz-RD

  profiles:
    active: dev 
        
  config:
    import: optional:configserver:http://localhost:8071 

#  cloud:
#    stream:
#      bindings:
#        myConsumer-in-0:
#          destination: my-topic
#          group: consumer
#      kafka:
#        binder:
#          brokers: localhost:9092

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true